FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_PRODUCT_API_URL
ARG VITE_ORDER_API_URL
ENV VITE_PRODUCT_API_URL=$VITE_PRODUCT_API_URL
ENV VITE_ORDER_API_URL=$VITE_ORDER_API_URL
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
